### ISSUE TITLE
JDK 21 w/ Gravit 5.5+

### ISSUE THREAD

**Issue by OzoneReloaded** [ijo42/GLauncherDockered#15]
Hello! Recent Gravit update to 5.5 with Java 21 seemed to break the deployment. Any fix planned?
Thanks!

**Comment by ijo42** [comment]
Hello!
I am surprised that someone uses this image, I myself have moved far away from the topic of GLauncher. But if you are interested, I will make an update

**Comment by OzoneReloaded** [comment]
That would be great! I've been using it for some time now and find it very convenient

**Comment by ijo42** [comment]
Main image updated in e62f03c5f09e39925e9e8685ce5c80e613fb5ea9
Check in [hub](https://hub.docker.com/layers/ijo42/glauncher/master/images/sha256-aec3780e02c118ede88ffc5b790f36c84b7f6275f1137c0cd297fa88fd7cbe57?context=explore) (ijo42/glauncher:master)
If arm64 need, let me know

**Comment by ijo42** [comment]
Main image updated in e62f03c5f09e39925e9e8685ce5c80e613fb5ea9
Check in [hub](https://hub.docker.com/layers/ijo42/glauncher/master/images/sha256-aec3780e02c118ede88ffc5b790f36c84b7f6275f1137c0cd297fa88fd7cbe57?context=explore) (ijo42/glauncher:master)
If arm64 need, let me know
